# -*- coding: utf-8 -*-
"""Unemployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139-2W5lT6NjZvulrBQSOe8rSY-lKK_SK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv("Unemployment.csv")
df

df.head(10)

df.info()

df.isnull().sum()

df.corr

df.describe()

df.columns

df.columns=["States"," Date", " Frequency", "Estimated Unemployment Rate",
  " Estimated Employed", " Estimated Labour Participation Rate",
       "Region", "longitude", "latitude"]

df

sns.countplot(x='Region',data=df)
plt.show

df.nunique()

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(df.corr())
plt.show()

sns.pairplot(df, size=5)

unemployment=df[["States","Region","Estimated Unemployment Rate"]]
figure=px.sunburst(unemployment,path=["Region","States"],
                  values="Estimated Unemployment Rate",
                  width=800,height=800,
                  title="Unemployment Rate In India")
figure.show()